name: ramazaan_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0-296.3.beta

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0              # For backend calls
  shared_preferences: ^2.2.2 # To store userId locally
  uuid: ^4.3.3

  cupertino_icons: ^1.0.8

  hive: ^2.2.3
  hive_flutter: ^1.1.0  # For local storage
  provider: ^6.1.1
  flutter_local_notifications: ^18.0.1 # For reminders
  timezone: ^0.9.4
  intl: ^0.20.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.4.8   # Required to run the command
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

